### ISSUE TITLE
PHRoyalTunnelCheat 3rd party updated code

### ISSUE THREAD

**Issue by jshaw93** [warpKaiba/TMpokeheroes#13]
Hullo, warp!  Been using your PH scripts for a bit now, and with the recent update to the Royal Tunnel I have taken the initiative to update your script to handle the new questions and claiming Regi eggs.

You can find the code here: https://github.com/jshaw93/PHRoyalTunnelCheat/blob/main/PHRoyalTunnelCheat.user.js

I will remove the repository if you wish for me to, or when you implement the code to your own repository!  Happy coding!
You may email me at LoreDevelopment@gmail.com

**Comment by Mushiyourdad69** [comment]
Hi i m using the code but my difficulty level isn't increasing like I completed the 20 levels of basic but i m still in basic.... Please tell me a solution

**Comment by jshaw93** [comment]
As soon as you finish the first set of basic you should have unlocked the next difficulty automatically.  Should see an Advanced path.
